### PR TITLE
More header cleanups from trees laying around.

### PR DESCRIPTION
**Pull request by robertlipe**
More C++-like
Whitespace fixes
Include guards

### CODE REVIEW

**Review by robertlipe — COMMENTED** [review]
LGTM

**Comment by tsteven4** [comment]
It looks like this broke compilation with gcc 5.4.0 on ubuntu 16.04.3.  
travis didn't see it because it is using gcc 4.8.4. Many others have 
reported this issue with gcc 5.4, a suggested fix is below.

Here is a fix that works with gcc 5.4.0:

> diff --git a/grtcirc.cc b/grtcirc.cc
> index 2f6102f..b6b6959 100644
> --- a/grtcirc.cc
> +++ b/grtcirc.cc
> @@ -85,7 +85,7 @@ double gcdist(double lat1, double lon1, double lat2, 
> double lon2)
>
>    res = asin(res);
>
> -  if (isnan(res) || (errno == EDOM)) { /* this should never happen: */
> +  if (std::isnan(res) || (errno == EDOM)) { /* this should never 
> happen: */
>      errno = 0; /* Math argument out of domain of function, */
>      return 0;  /* or value returned is not a number */
>    }

Here is the problem reported with gcc 5.4.0:

> g++ -std=gnu++11  -g -O2 -Wall -fPIC -c -I. 
> -I/usr/include/x86_64-linux-gnu/qt5  -DHAVE_CONFIG_H -DNEW_STRINGS 
> grtcirc.cc -o grtcirc.o
> grtcirc.cc: In function ‘double gcdist(double, double, double, double)’:
> grtcirc.cc:88:16: error: ‘isnan’ was not declared in this scope
>    if (isnan(res) || (errno == EDOM)) { /* this should never happen: */
>                 ^
> grtcirc.cc:88:16: note: suggested alternative:
> In file included from /usr/include/c++/5/random:38:0,
>                  from /usr/include/c++/5/bits/stl_algo.h:66,
>                  from /usr/include/c++/5/algorithm:62,
>                  from 
> /usr/include/x86_64-linux-gnu/qt5/QtCore/qglobal.h:85,
>                  from /usr/include/x86_64-linux-gnu/qt5/QtCore/qchar.h:37,
>                  from 
> /usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h:41,
>                  from /usr/include/x86_64-linux-gnu/qt5/QtCore/QString:1,
>                  from gbfile.h:30,
>                  from defs.h:33,
>                  from grtcirc.cc:22:
> /usr/include/c++/5/cmath:641:5: note:   ‘std::isnan’
>      isnan(_Tp __x)
>      ^
> Makefile:128: recipe for target 'grtcirc.o' failed

> $ g++ --version
> g++ (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609
> Copyright (C) 2015 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions. There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR 
> PURPOSE.

**Comment by GPSBabelDeveloper** [comment]
Sorry about that. I'm surprised we don't run into std:: namespace issues
more often. Fixed in https://github.com/gpsbabel/gpsbabel/pull/100
